#!/bin/sh
# gen_snkv_header.sh — Generate snkv.h, a single-file amalgamation.
#
# Usage:
#   sh scripts/gen_snkv_header.sh > snkv.h
#
# The output contains the full public API + all implementation.
# Include it from exactly ONE .c file to compile the entire library:
#
#   #include "snkv.h"
#   int main() { ... }
#
# Compile: gcc myapp.c -o myapp        (no -Iinclude, no libsnkv.a)

SRCDIR="$(cd "$(dirname "$0")/.." && pwd)"
INCDIR="$SRCDIR/include"
CDIR="$SRCDIR/src"

# Strip lines that include internal project headers.
# Keeps all system <...> includes except <sqliteInt.h> (used by os_kv.c).
# Exception: #include "windows.h" (used by os_win.h) is converted to a
# platform-guarded #include <windows.h> so it is included on Windows but
# silently skipped on Linux/macOS.
strip_local_includes() {
  awk '
    /^[[:space:]]*#[[:space:]]*include[[:space:]]*"windows\.h"/ {
      print "#ifdef _WIN32"
      print "#include <windows.h>"
      print "#endif"
      next
    }
    /^[[:space:]]*#[[:space:]]*include[[:space:]]*"[^"]*"/ { next }
    /^[[:space:]]*#[[:space:]]*include[[:space:]]*<sqliteInt\.h>/    { next }
    { print }
  '
}

emit() {
  echo "/****** $1 ******/"
  strip_local_includes < "$2"
  echo ""
}

# emit_monocypher — like emit() but renames monocypher's internal i64/u64
# typedefs to mc_i64/mc_u64 to avoid conflicts with SQLite's i64/u64.
emit_monocypher() {
  echo "/****** $1 ******/"
  strip_local_includes < "$2" | sed \
    -e 's/\btypedef int64_t  i64;\b/typedef int64_t  mc_i64;/' \
    -e 's/\btypedef uint64_t u64;\b/typedef uint64_t mc_u64;/' \
    -e 's/\bi64\b/mc_i64/g' \
    -e 's/\bu64\b/mc_u64/g'
  echo ""
}

# Emit a range of lines from a file (1-based, inclusive).
# Usage: emit_lines FILE START END
emit_lines() {
  sed -n "${2},${3}p" "$1" | strip_local_includes
}

# Emit the public API from kvstore.h, stripping its own _KVSTORE_H_ include
# guards.  All other transformations (local-include removal, windows.h quoting)
# are handled by strip_local_includes.  Nothing API-related is hardcoded here:
# add a new constant, struct field, or function to kvstore.h and it
# automatically appears in snkv.h on the next `make snkv.h`.
emit_kvstore_public() {
  sed \
    -e '/^#ifndef _KVSTORE_H_$/d' \
    -e '/^#define _KVSTORE_H_$/d' \
    -e '/^#endif \/\* _KVSTORE_H_ \*\/$/d' \
    < "$1" | strip_local_includes
}

# ============================================================
# Part 1: File preamble (snkv.h-specific) + public API from kvstore.h.
#
# Only the snkv.h include guard, _GNU_SOURCE guard, and the usage comment
# are hardcoded here.  Every type, constant, struct, and function
# declaration is derived directly from include/kvstore.h.
# ============================================================
cat << 'FILE_HEADER'
/* SPDX-License-Identifier: Apache-2.0 */
/*
** snkv.h — Single-file amalgamation for the SNKV key-value store.
**
** Auto-generated by scripts/gen_snkv_header.sh — do not edit by hand.
**
** SNKV is a persistent, ACID-compliant key-value store built on
** SQLite's B-tree / pager / WAL engine.
**
** Usage (C) — in exactly ONE .c file:
**
**     #define SNKV_IMPLEMENTATION
**     #include "snkv.h"
**     int main() { ... }
**
** Compile (Linux/macOS):  gcc myapp.c -o myapp
** Compile (Windows/MSYS): gcc myapp.c -o myapp.exe
**
** Usage (C++) — compile the implementation as C, use the API from C++:
**
**     // snkv_impl.c (compile as C)
**     #define SNKV_IMPLEMENTATION
**     #include "snkv.h"
**
**     // myapp.cpp (compile as C++)
**     #include "snkv.h"
**     int main() { ... }
*/
#ifndef SNKV_H
#define SNKV_H
#pragma once

/* Suppress MSVC "unsafe function" warnings (sprintf, strcpy, etc.) */
#if defined(_MSC_VER) && !defined(_CRT_SECURE_NO_WARNINGS)
# define _CRT_SECURE_NO_WARNINGS
#endif

/* _GNU_SOURCE must be defined before any system headers for mremap() etc. */
#if defined(__GNUC__) && !defined(_GNU_SOURCE)
# define _GNU_SOURCE
#endif

FILE_HEADER

emit_kvstore_public "$INCDIR/kvstore.h"

echo ""

# ============================================================
# Part 2: Implementation — all internal headers then all sources.
#
# sqliteInt.h includes sub-headers at specific points WITHIN the file:
#   Line 634: #include "hash.h"  /  #include "parse.h"
#   Line 1428: #include "os.h"  /  #include "pager.h"  /  #include "btree.h"
#   Line 1522: #include "pcache.h"  /  #include "mutex.h"
#
# We must interleave sub-headers at those exact positions so types
# are defined before they are used. We split sqliteInt.h into sections
# and inline the sub-headers between them.
# ============================================================

echo ""
echo "/* =================================================================="
echo "** IMPLEMENTATION"
echo "**"
echo "** Define SNKV_IMPLEMENTATION in exactly ONE .c file before including"
echo "** this header to compile the library.  All other files (including"
echo "** .cpp files) get only the public API declarations above."
echo "**"
echo "** Example:"
echo "**   // snkv_impl.c"
echo "**   #define SNKV_IMPLEMENTATION"
echo "**   #include \"snkv.h\""
echo "** ================================================================== */"
echo "#ifdef SNKV_IMPLEMENTATION"
echo ""

# --- Phase A: Headers that must come before sqliteInt.h ---
for h in msvc.h vxworks.h sqlite3.h sqliteLimit.h; do
  emit "include/$h" "$INCDIR/$h"
done

# --- Phase B: sqliteInt.h split into sections with sub-headers interleaved ---
#
# We use grep -n to find the exact line numbers of the #include directives
# so this stays correct even if sqliteInt.h is edited.

SQLITEINT="$INCDIR/sqliteInt.h"

# Find line numbers of the key #include directives
LINE_HASH=$(grep -n '#include "hash.h"' "$SQLITEINT" | head -1 | cut -d: -f1)
LINE_PARSE=$(grep -n '#include "parse.h"' "$SQLITEINT" | head -1 | cut -d: -f1)
LINE_OS=$(grep -n '#include "os.h"' "$SQLITEINT" | head -1 | cut -d: -f1)
LINE_PAGER=$(grep -n '#include "pager.h"' "$SQLITEINT" | head -1 | cut -d: -f1)
LINE_BTREE=$(grep -n '#include "btree.h"' "$SQLITEINT" | head -1 | cut -d: -f1)
LINE_PCACHE=$(grep -n '#include "pcache.h"' "$SQLITEINT" | head -1 | cut -d: -f1)
LINE_MUTEX=$(grep -n '#include "mutex.h"' "$SQLITEINT" | head -1 | cut -d: -f1)
LINE_END=$(wc -l < "$SQLITEINT")

echo "/****** include/sqliteInt.h (section 1: base types) ******/"
emit_lines "$SQLITEINT" 1 $((LINE_HASH - 1))

# Inline hash.h and parse.h (where sqliteInt.h line 634-635 would include them)
emit "include/hash.h" "$INCDIR/hash.h"
emit "include/parse.h" "$INCDIR/parse.h"

echo "/****** include/sqliteInt.h (section 2: after hash/parse, before os/btree) ******/"
emit_lines "$SQLITEINT" $((LINE_PARSE + 1)) $((LINE_OS - 1))

# Inline os_setup.h, os.h, pager.h, btree.h (where sqliteInt.h line 1428-1430 includes them)
emit "include/os_setup.h" "$INCDIR/os_setup.h"
emit "include/os.h" "$INCDIR/os.h"
emit "include/pager.h" "$INCDIR/pager.h"
emit "include/btree.h" "$INCDIR/btree.h"

echo "/****** include/sqliteInt.h (section 3: VDBE stubs) ******/"
emit_lines "$SQLITEINT" $((LINE_BTREE + 1)) $((LINE_PCACHE - 1))

# Inline pcache.h and mutex.h (where sqliteInt.h line 1522-1523 includes them)
emit "include/pcache.h" "$INCDIR/pcache.h"
emit "include/mutex.h" "$INCDIR/mutex.h"

echo "/****** include/sqliteInt.h (section 4: remainder) ******/"
emit_lines "$SQLITEINT" $((LINE_MUTEX + 1)) "$LINE_END"

# --- Phase C: Headers that depend on sqliteInt.h + sub-headers ---
for h in btreeInt.h wal.h os_common.h os_win.h; do
  emit "include/$h" "$INCDIR/$h"
done

# kvstore.h public API (including compat macros and snkv_malloc/snkv_free)
# was already emitted in Part 1.  Define its include guard so that the
# stripped #include "kvstore.h" inside kvstore.c becomes a no-op.
echo "#define _KVSTORE_H_"
echo ""

# monocypher.h provides the types (crypto_argon2_config etc.) needed by
# the encryption layer inlined in kvstore.c.  Emit it now; its include
# guard prevents re-emission when monocypher.c itself is later processed.
emit "include/monocypher/monocypher.h" "$INCDIR/monocypher/monocypher.h"
echo "#define MONOCYPHER_H"
echo ""

# --- Phase D: All .c source files ---
SOURCES="
  global.c
  malloc.c
  mem1.c
  util.c
  printf.c
  random.c
  fault.c
  hash.c
  bitvec.c
  pcache.c
  pcache1.c
  mutex.c
  mutex_noop.c
  mutex_unix.c
  mutex_w32.c
  os.c
  os_unix.c
  os_win.c
  os_kv.c
  pager.c
  wal.c
  memjournal.c
  btree.c
  btmutex.c
  status.c
  threads.c
  kvstore.c
"

for s in $SOURCES; do
  emit "src/$s" "$CDIR/$s"
done

# Monocypher is emitted with i64/u64 renamed to avoid SQLite typedef conflicts
emit_monocypher "src/monocypher/monocypher.c" "$CDIR/monocypher/monocypher.c"

# ============================================================
# Part 3: Close the include guard
# ============================================================
echo "#endif /* SNKV_IMPLEMENTATION */"
echo ""
echo "#endif /* SNKV_H */"
